Prueba/Models/Administrador.cs
using System;
using System.Collections.Generic;

namespace Prueba.Models;

public partial class Administrador
{
    public int IdAdministrador { get; set; }

    public int IdCondominio { get; set; }

    public string IdUsuario { get; set; } = null!;

    public string Cargo { get; set; } = null!;

    public bool Activo { get; set; }

    public virtual Condominio IdCondominioNavigation { get; set; } = null!;

    public virtual AspNetUser IdUsuarioNavigation { get; set; } = null!;
}

Prueba/Controllers/AdministradorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.DotNet.Scaffolding.Shared.Project;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using Prueba.Areas.Identity.Data;
using Prueba.Context;
using Prueba.Core.Repositories;
using Prueba.Models;
using Prueba.Repositories;
using Prueba.Services;
using Prueba.Utils;
using Prueba.ViewModels;
using System.Net;

namespace Prueba.Controllers
{
    [Authorize(Policy = "RequireAdmin")]

    public class AdministradorController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUserStore<ApplicationUser> _userStore;
        private readonly IEmailService _serviceEmail;
        private readonly IPDFServices _servicePDF;
        private readonly IManageExcel _manageExcel;
        private readonly IReportesRepository _repoReportes;
        private readonly IRelacionGastoRepository _repoRelacionGasto;
        private readonly NuevaAppContext _context;

        /// <summary>
        /// 
        /// </summary>
        /// <param name="unitOfWork"></param>
        /// <param name="signInManager"></param>
        /// <param name="userManager"></param>
        /// <param name="userStore"></param>
        /// <param name="serviceEmail"></param>
        /// <param name="manageExcel"></param>
        /// <param name="context"></param>
        public AdministradorController(IUnitOfWork unitOfWork,
            SignInManager<ApplicationUser> signInManager,
            UserManager<ApplicationUser> userManager,
            IUserStore<ApplicationUser> userStore,
            IEmailService serviceEmail,
            IPDFServices PDFService,
            IManageExcel manageExcel,
            IReportesRepository repoReportes,
            IRelacionGastoRepository repoRelacionGasto,
            NuevaAppContext context)
        {
            _unitOfWork = unitOfWork;
            _signInManager = signInManager;
            _userManager = userManager;
            _userStore = userStore;
            _serviceEmail = serviceEmail;
            _servicePDF = PDFService;
            _manageExcel = manageExcel;
            _repoReportes = repoReportes;
            _repoRelacionGasto = repoRelacionGasto;
            _context = context;
        }

        public IActionResult PruebaPDF()
        {
            var data = _servicePDF.ExamplePDF();
            Stream stream = new MemoryStream(data);
            return File(stream, "application/pdf", "detalleventa.pdf");
        }

        /// <summary>
        /// Busca los condominios asignados a un Administrador
        /// </summary>
        /// <returns>Vista con todos los condominios</returns>
        public async Task<IActionResult> Index()
        {
            try
            {
                //CON EL ID DEL USUARIO LOGEADO BUSCAR SUS CONDOMINIOS ASIGNADOS
                var idAdministrador = TempData.Peek("idUserLog").ToString();

                //CARGAR LIST DE CONDOMINIOS
                var condominios = _context.Condominios.Include(c => c.IdAdministradorNavigation)
                    //.Include(c => c.Inmuebles)
                    .Where(c => c.IdAdministrador == idAdministrador);

                //foreach (var item in condominios)
                //{
                //    var inmuebles = _context.Inmuebles.Include(c => c.IdCondominioNavigation)
                //        .Where(c => c.IdCondominio == item.IdCondominio);
                //}

                var condominiosModel = await condominios.ToListAsync();

                TempData.Keep();

                return View(condominiosModel);

            }
            catch (Exception ex)
            {
                var modeloError = new ErrorViewModel()
                {
                    RequestId = ex.Message
                };

                return View("Error", modeloError);
            }

        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id">id del condominio seleccionado</param>
        /// <returns>Vista del dashboard</returns>
        public async Task<IActionResult> Dashboard(int id)
        {
            try
            {
                // GUARDAR ID CONDOMINIO PARA SELECCIONAR SUS CUENTAS CONTABLES
                TempData["idCondominio"] = id.ToString();
                var modelo = await _repoReportes.InformacionGeneral(id);
                return View(modelo);

            }
            catch (Exception ex)
            {
                var modeloError = new ErrorViewModel()
                {
                    RequestId = ex.Message
                };

                return View("Error", modeloError);
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Deudores()
        {
            try
            {
                int idCondominio = Convert.ToInt32(TempData.Peek("idCondominio").ToString());

                var modelo = await _repoReportes.LoadDataDeudores(idCondominio);

                TempData.Keep();

                return View(modelo);
            }
            catch (Exception ex)
            {
                var modeloError = new ErrorViewModel()
                {
                    RequestId = ex.Message
                };

                return View("Error", modeloError);
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult ConfirmarPagoRecibido(int id)
        {
            try
            {
                TempData["idPagoConfirmar"] = id.ToString();
                return View();
            }
            catch (Exception ex)
            {
                var modeloError = new ErrorViewModel()
                {
                    RequestId = ex.Message
                };

                return View("Error", modeloError);
            }

        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> ConfirmarPagoRecibidoPost()
        {
            try
            {
                int id = Convert.ToInt32(TempData.Peek("idPagoConfirmar").ToString());

                int idCondominio = Convert.ToInt32(TempData.Peek("idCondominio").ToString());

                // buscar pago
                var pago = await _context.PagoRecibidos.FindAsync(id);

                if (pago != null)
                {
                    // buscar propiedad                   

                    var recibo = (from c in _context.PagosRecibos
                                  join r in _context.ReciboCobros
                                  on c.IdRecibo equals r.IdReciboCobro
                                  where c.IdPago == pago.IdPagoRecibido
                                  select r).FirstOrDefault();

                    if (recibo != null)
                    {
                        var propiedad = await _context.Propiedads.FindAsync(recibo.IdPropiedad);

                        var relacion = await _context.PagosRecibos.Where(c => c.IdPago == pago.IdPagoRecibido).ToListAsync();

                        var reciboActual = (from r in relacion
                                            join rc in _context.ReciboCobros
                                            on r.IdRecibo equals rc.IdReciboCobro
                                            where r.IdPago == pago.IdPagoRecibido
                                            select rc).FirstOrDefault();

                        // buscar subcuenta contable donde esta el pago del condominio
                        var cuentaCondominio = from s in _context.SubCuenta
                                               join cc in _context.CodigoCuentasGlobals
                                               on s.Id equals cc.IdSubCuenta
                                               where cc.IdCondominio == idCondominio
                                               //where s.IdCuenta == 15 && s.Codigo == "01"
                                               select s;

                        // buscar referencia si tiene
                        var referencias = new List<ReferenciasPr>();

                        if (pago.FormaPago)
                        {
                            referencias = await _context.ReferenciasPrs.Where(c => c.IdPagoRecibido == pago.IdPagoRecibido).ToListAsync();
                        }

                        if (reciboActual == null)
                        {
                            foreach (var r in referencias)
                            {
                                _context.Remove(r);
                            }
                            _context.PagoRecibidos.Remove(pago);
                            await _context.SaveChangesAsync();

                            var modeloError = new ErrorViewModel()
                            {
                                RequestId = "El Recibo asignado a este Pago fue eliminado! Este pago será eliminado"
                            };

                            return View("Error", modeloError);
                        }

                        try
                        {
                            // se pago solo el recibo del mes actual
                            using (var dbContext = new NuevaAppContext())
                            {

                                // ADD PAGOS ABONADOS SOBRE LOS RECIBOS

                                if (pago.MontoRef == reciboActual.Monto || propiedad.Saldo == pago.MontoRef || (pago.MontoRef == (propiedad.Saldo + propiedad.Deuda))) //|| reciboActual.Abonado > reciboActual.Monto

Prueba/Views/Administrador/ConfirmarPagoRecibido.cshtml
@{
    ViewData["Title"] = "Pagos";
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";
}
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    @*<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Confirmar Pago</h1>
    </div>*@

    <!-- Content Row -->
    <div class="row justify-content-center">
        <div class="col-lg-4 mb-4">
            <!-- Illustrations -->
            <!-- DataTales Example -->
            <div class="card shadow mb-4 bg-content-bg">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">
                    </h6>

                </div>

                <div class="card-body">
                    <div class="table-responsive">
                        <h6 class="m-0 font-weight-bold text-primary">
                            ¿Seguro que quiere confirmar este pago?
                        </h6>
                        <div>
                            <form asp-action="ConfirmarPagoRecibidoPost">
                                <p>Al confirmar el pago se verá reflejado en el Libro diario</p>
                                <button class="btn btn-primary" type="submit">Si</button>
                                <a asp-action="PagosRecibidos" class="btn">No</a>
                                <div class="col-md-6 mt-3">
                                    <label for="last-name-column">¿Desea enviar correo a los propietarios?</label>
                                    <select id="selectEnviarCorreo" class="form-select nav-tabs-selector" onchange="mostrarModal()">
                                        <option value="no">No</option>
                                        <option value="si">Sí</option>
                                    </select>
                                </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Modal -->
<div id="exampleModal" class="modal fade" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Ingresar datos del correo</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="mb-3">
                        <label for="usuario" class="form-label">Correo Electrónico</label>
                        <input type="email" class="form-control" id="usuario" name="usuario" required>
                    </div>
                    <div class="mb-3">
                        <label for="contrasena" class="form-label">Password</label>
                        <input type="password" class="form-control" id="contrasena" name="contrasena" required>
                    </div>
                    <button type="button" id="enviarDatos" class="btn btn-primary">Enviar</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.min.js"></script>
<script>
    $("#selectEnviarCorreo").on("click", function () {
        // Si el valor del select es "si", abre el modal
        if (this.value === "si") {
            // Abre el modal
            $("#exampleModal").modal("show");
        }
    });
    $(document).ready(function () {
        $("#enviarDatos").click(function () {
            // Obtener valores del formulario
            var usuario = $("#usuario").val();
            var contrasena = $("#contrasena").val();

            // Realizar solicitud AJAX
            $.ajax({
                url: '/Administrador/UsuarioContraseña',
                type: 'POST',
                data: { usuario: usuario, contrasena: contrasena },
                success: function (response) {
                    // console.log(response);
                    // alert(response.message); // Mostrar mensaje de éxito o error
                },
                error: function (error) {
                    console.error(error);
                    // alert('Error en la solicitud AJAX');
                }
            });
        });
    });

</script>

Prueba/Views/Administrador/CrearSubCuenta.cshtml
@using Newtonsoft.Json.Linq;

@model SubcuentaCascadingVM
@{
    ViewData["Title"] = "Sub Cuentas";
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";
}
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        @*<h1 class="h3 mb-0 text-gray-800">Formulario para crear sub cuenta</h1>*@
    </div>

    <!-- Content Row -->
    <div class="row justify-content-center">
        <div class="col-lg-7">
            <!-- Default Card Example -->
            <div class="card shadow mb-4 bg-content-bg">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">
                        Nueva Sub Cuenta
                    </h6>
                </div>
                <div class="card-body">
                    <div >


                        <div class="form-body">

                            <div class="row">

                                @using (Html.BeginForm("CrearSubCuentaPost", "Administrador", FormMethod.Post))
                                {

                                    <div>
                                        <div id="multi-step-form-container">
                                            <!-- LineaProgreso -->
                                            <ul class="form-stepper form-stepper-horizontal text-center mx-auto pl-0">
                                                <!-- Paso 1 -->
                                                <li class="form-stepper-active text-center form-stepper-list" step="1">
                                                    <a class="mx-2">
                                                        <span class="form-stepper-circle">
                                                            <span>1</span>
                                                        </span>
                                                        <div class="label">Seleccionar</div>
                                                    </a>
                                                </li>
                                                <!-- Paso 2 -->
                                                <li class="form-stepper-unfinished text-center form-stepper-list" step="2">
                                                    <a class="mx-2">
                                                        <span class="form-stepper-circle text-muted">
                                                            <span>2</span>
                                                        </span>
                                                        <div class="label text-muted">Seleccionar</div>
                                                    </a>
                                                </li>
                                                <!-- Paso 3 -->
                                                <li class="form-stepper-unfinished text-center form-stepper-list" step="3">
                                                    <a class="mx-2">
                                                        <span class="form-stepper-circle text-muted">
                                                            <span>3</span>
                                                        </span>
                                                        <div class="label text-muted">Seleccionar</div>
                                                    </a>
                                                </li>
                                            </ul>
                                            <!-- Step Form Content -->
                                            <div >
                                                <!-- Pso 1 -->
                                                <section id="step-1" class="form-step">

                                                  

                                                    <h2 class="font-normal">Seleccionar una Clase</h2>
                                                    <!-- Step 1 input fields -->
                                                    <div class="mt-3">
                                                        @Html.DropDownListFor(m => m.IdClase, Model.Clases, "Seleccione una Clase", new {@class = "form-control"})
                                                        <br />                                             
                                                    </div>
                                                    <div class="mt-3">
                                                        @*<button class="btn-primary btn button btn-navigate-form-step" name="act" id='submito' disabled step_number="2">Siguiente</button>*@
                                                        <button class="btn btn-primary btnbutton btn-navigate-form-step" type="button" step_number="2">Siguiente</button>
                                                    </div>
                                                </section>
                                                <!-- Pso 2 -->
                                                <section id="step-2" class="form-step d-none">
                                                    <h2 class="font-normal">Seleccionar un Grupo</h2>
                                                    <!-- Step 2 input fields -->
                                                    <div class="mt-3">
                                                        @Html.DropDownListFor(m => m.IdGrupo, Model.Grupos, "Seleccionar", new {@class = "form-control"})
                                                        <br />
                                                  
                                                    </div>
                                                    <div class="mt-3">
                                                        <button class="btn btn-primary btnbutton btn-navigate-form-step" type="button" step_number="1">Atras</button>
                                                        <button class="btn btn-primary btnbutton btn-navigate-form-step" type="button" step_number="3">Siguiente</button>
                                                    </div>
                                                </section>
                                                <!-- Pso 3 Content -->
                                                <section id="step-3" class="form-step d-none">
                                                    <h2 class="font-normal">Seleccionar una Cuenta</h2>
                                                    <!-- Step 3 input fields -->
                                                    <div class="mt-3">
                                                        @Html.DropDownListFor(m => m.IdCuenta, Model.Cuentas, "Seleccionar", new {@class = "form-control"})
                                                        <br />
                                                

                                                        <div class="row">
                                                            <!-- Descricción -->
                                                            <div class="col-md-6 col-12">
                                                                <div class="form-group has-icon-left mandaory">
                                                                    <label for="last-name-column">Descripción</label>
                                                                    <div class="position-relative">
                                                                        <input class="form-control" type="text" placeholder="Descripción" asp-for="Descripcion" />
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <!-- Código -->
                                                            <div class="col-md-6 col-12">
                                                                <div class="form-group has-icon-left mandaory">
                                                                    <label for="last-name-column">Código</label>
                                                                    <div class="position-relative">
                                                                        <input class="form-control" type="text" placeholder="Código" asp-for="Codigo" />
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="mt-3">
                                                        <button class="btn-primary btn button btn-navigate-form-step" type="button" step_number="2">Atras</button>

                                                        <button class="btn btn-primary" type="submit">Guardar</button>
                                                    </div>
                                                </section>
                                            </div>
                                        </div>
                                    </div>
                                }

                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    <!-- Content Row -->
</div>




@*<body>

    @using (Html.BeginForm("CrearSubCuentaPost", "Administrador", FormMethod.Post))
    {
        @Html.DropDownListFor(m => m.IdClase, Model.Clases, "Seleccione una Clase", new {@class = "form-control"})
        <br />
        <br />
        @Html.DropDownListFor(m => m.IdGrupo, Model.Grupos, "Seleccione un Grupo", new {@class = "form-control"})
        <br />
        <br />
        @Html.DropDownListFor(m => m.IdCuenta, Model.Cuentas, "Seleccione una Cuenta", new {@class = "form-control"})
        <br />
        <br />

        <label>Descripción</label>
        <input type="text" placeholder="Descripción" asp-for="Descripcion"/>

        <label>Código</label>
        <input type="text" placeholder="Código" asp-for="Codigo"/>

        <input class="btn btn-primary" type="submit" value="Submit" />
    }



</body>*@

@section Scripts{

    <script type="text/javascript">
        $(function () {
            $("select").each(function () {
                if ($(this).find("option").length <= 1) {
                    $(this).attr("disabled", "disabled");
                }
            });
 
            $("select").change(function () {
                var value = 0;
                if ($(this).val() != "") {
                    value = $(this).val();
                }
                var id = $(this).attr("id");
                var dataRequest = {
                    tipo: id,
                    valor: value
                }
                $.ajax({
                    type: "POST",
                    url: "/Administrador/AjaxMethod",
                    data: dataRequest,
                    //contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (response) {
                        console.log(response);
                        var dropDownId;
                        var list;
                        switch (id) {
                            case "IdClase":
                                list = response.grupos;
                                DisableDropDown("#IdGrupo");
                                DisableDropDown("#IdCuenta");
                                PopulateDropDown("#IdGrupo", list);
                                break;
                            case "IdGrupo":
                                dropDownId = "#IdCuenta";
                                list = response.cuentas;
                                DisableDropDown("#IdCuenta");
                                PopulateDropDown("#IdCuenta", list);
                                break;
                        }
                       
                    },
                    failure: function (response) {
                        alert(response.responseText);
                    },
                    error: function (response) {
                        alert(response.responseText);
                    }
                });
            });
        });
 
        function DisableDropDown(dropDownId) {
            $(dropDownId).attr("disabled", "disabled");
            $(dropDownId).empty().append('<option selected="selected" value="0">Seleccionar</option>');
        }
 
        function PopulateDropDown(dropDownId, list) {
            if (list != null && list.length > 0) {
                $(dropDownId).removeAttr("disabled");
                $.each(list, function () {
                    $(dropDownId).append($("<option></option>").val(this['value']).html(this['text']));
                });
            }
        }
 
        $(function () {
            if ($("#IdClase").val() != "" && $("#IdGrupo").val() != "" && $("#IdCuenta").val() != "") {
                var message = "Clase: " + $("#IdClase option:selected").text();
                message += "\nGrupo: " + $("#IdGrupo option:selected").text();
                message += "\nCuenta: " + $("#IdCuenta option:selected").text();
                alert(message);
            }
        });

    </script>

}

Prueba/Views/Administrador/Dashboard.cshtml
@using Prueba.ViewModels

@model InformacionDashboardVM

@{
    ViewData["Title"] = "Dashboard";
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";
}

<partial name="_Dashboard" model="Model"/>

Prueba/Views/Administrador/DetalleRecibo.cshtml
@model Prueba.ViewModels.DetalleReciboTransaccionesVM
@{
    ViewData["Title"] = "Detalles";
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";
}
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-around mb-4">
        <a class="btn btn-light mb-3" asp-route-id="@Model.Recibo.IdReciboCobro" asp-controller="RelacionGastos" asp-action="DetalleReciboTransaccionesPDF">PDF</a>
    </div>
    <!-- Content Row -->
    <div class="row">
        <div class="col-lg-12">
            <!-- Default Card Example -->
            <div class="card shadow mb-4 bg-content-bg">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">
                        Detalles de Recibo
                    </h6>
                </div>
                <div class="card-body">
                    <div class="form form-horizontal">
                        <div class="form-body">
                            <partial name="_DetalleReciboTransacciones" model="Model" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Prueba/Views/Administrador/Deudores.cshtml
@using Prueba.ViewModels

@model RecibosCreadosVM
@{
    ViewData["Title"] = "Deudores";
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";
}

<div class="container-fluid">
    <!-- Page Heading -->
@*     <div class="d-sm-flex align-items-center justify-content-around mb-4">
        <a class="btn btn-light mb-3" asp-controller="Reportes" asp-action="DeudoresResumenPDF">PDF</a>
    </div> *@
    <div class="d-sm-flex align-items-center justify-content-around mb-4">
        <a asp-controller="Reportes" asp-action="DeudoresResumenPDF"
            class="d-sm-inline-block btn btn-sm btn-danger shadow-sm">
            <i class="fas fa-download fa-sm text-white-50"></i> Generar
            PDF
        </a>

        <a asp-controller="Reportes" asp-action="DeudoresExcel"
        class="d-sm-inline-block btn btn-sm btn-success shadow-sm">
            <i class="fas fa-download fa-sm text-white-50"></i> Generar
            Excel
        </a>
    </div>
    <partial name="_Deudores" model="Model" />
</div>