Prueba/Models/AnticipoNomina.cs
using System;
using System.Collections.Generic;

namespace Prueba.Models;

public partial class AnticipoNomina
{
    public int IdAnticipoNomina { get; set; }

    public int IdEmpleado { get; set; }

    public decimal Monto { get; set; }

    public DateTime Fecha { get; set; }

    public bool Activo { get; set; }

    public int? IdPagoEmitido { get; set; }

    public virtual Empleado IdEmpleadoNavigation { get; set; } = null!;

    public virtual PagoEmitido? IdPagoEmitidoNavigation { get; set; }
}

Prueba/Controllers/AnticipoNominasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Prueba.Context;
using Prueba.Models;
using Prueba.Repositories;
using Prueba.Services;
using Prueba.ViewModels;

namespace Prueba.Controllers
{
    public class AnticipoNominasController : Controller
    {
        private readonly IPDFServices _servicesPDF;
        private readonly IPagosEmitidosRepository _repoPagosEmitidos;
        private readonly NuevaAppContext _context;

        public AnticipoNominasController(IPDFServices servicesPDF,
            IPagosEmitidosRepository repoPagosEmitidos,
            NuevaAppContext context)
        {
            _servicesPDF = servicesPDF;
            _repoPagosEmitidos = repoPagosEmitidos;
            _context = context;
        }

        //// GET: AnticipoNominas
        //public async Task<IActionResult> Index()
        //{
        //    var nuevaAppContext = _context.AnticipoNominas.Include(a => a.IdEmpleadoNavigation);
        //    return View(await nuevaAppContext.ToListAsync());
        //}
        // GET: AnticipoNominas
        public async Task<IActionResult> Index(int id)
        {
            var nuevaAppContext = _context.AnticipoNominas
                .Include(b => b.IdEmpleadoNavigation)
                .Include(b => b.IdPagoEmitidoNavigation)
                .Where(c => c.IdEmpleado == id);

            return View(await nuevaAppContext.ToListAsync());
        }


        // GET: AnticipoNominas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var anticipoNomina = await _context.AnticipoNominas
                .Include(a => a.IdEmpleadoNavigation)
                .FirstOrDefaultAsync(m => m.IdAnticipoNomina == id);
            if (anticipoNomina == null)
            {
                return NotFound();
            }

            return View(anticipoNomina);
        }

        // GET: AnticipoNominas/Create
        public IActionResult Create()
        {
            ViewData["IdEmpleado"] = new SelectList(_context.Empleados, "IdEmpleado", "Nombre");
            return View();
        }

        // POST: AnticipoNominas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdAnticipoNomina,IdEmpleado,Monto,Fecha,Activo")] AnticipoNomina anticipoNomina)
        {
            ModelState.Remove(nameof(anticipoNomina.IdEmpleadoNavigation));

            if (ModelState.IsValid)
            {
                _context.Add(anticipoNomina);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdEmpleado"] = new SelectList(_context.Empleados, "IdEmpleado", "Nombre", anticipoNomina.IdEmpleado);
            return View(anticipoNomina);
        }

        // GET: AnticipoNominas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var anticipoNomina = await _context.AnticipoNominas.FindAsync(id);
            if (anticipoNomina == null)
            {
                return NotFound();
            }
            ViewData["IdEmpleado"] = new SelectList(_context.Empleados, "IdEmpleado", "Nombre", anticipoNomina.IdEmpleado);
            return View(anticipoNomina);
        }

        // POST: AnticipoNominas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdAnticipoNomina,IdEmpleado,Monto,Fecha,Activo")] AnticipoNomina anticipoNomina)
        {
            if (id != anticipoNomina.IdAnticipoNomina)
            {
                return NotFound();
            }

            ModelState.Remove(nameof(anticipoNomina.IdEmpleadoNavigation));

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(anticipoNomina);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnticipoNominaExists(anticipoNomina.IdAnticipoNomina))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdEmpleado"] = new SelectList(_context.Empleados, "IdEmpleado", "Nombre", anticipoNomina.IdEmpleado);
            return View(anticipoNomina);
        }

        // GET: AnticipoNominas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var anticipoNomina = await _context.AnticipoNominas
                .Include(a => a.IdEmpleadoNavigation)
                .FirstOrDefaultAsync(m => m.IdAnticipoNomina == id);
            if (anticipoNomina == null)
            {
                return NotFound();
            }

            return View(anticipoNomina);
        }

        // POST: AnticipoNominas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var anticipoNomina = await _context.AnticipoNominas.FindAsync(id);
            if (anticipoNomina != null)
            {
                _context.AnticipoNominas.Remove(anticipoNomina);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AnticipoNominaExists(int id)
        {
            return _context.AnticipoNominas.Any(e => e.IdAnticipoNomina == id);
        }

        public IActionResult ConfirmarPago(PagoAnticipoNominaVM modelo)
        {
            return View(modelo);
        }
        public async Task<IActionResult> RegistrarAnticipoNomina()
        {
            var idCondominio = Convert.ToInt32(TempData.Peek("idCondominio").ToString());

            // cargar formulario
            var modelo = await _repoPagosEmitidos.FormPagoAnticipoNomina(idCondominio);
            // usar el repositorio?
            TempData.Keep();
            return View(modelo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegistrarAnticipoNomina(PagoAnticipoNominaVM modelo)
        {
            try
            {
                if (modelo.IdCodigoCuentaCaja != 0 || modelo.IdCodigoCuentaBanco != 0)
                {
                    modelo.IdCondominio = Convert.ToInt32(TempData.Peek("idCondominio").ToString());

                    if (modelo.Pagoforma == FormaPago.Transferencia)
                    {
                        var existPagoTransferencia = from pago in _context.PagoEmitidos
                                                     join referencia in _context.ReferenciasPes
                                                     on pago.IdPagoEmitido equals referencia.IdPagoEmitido
                                                     where pago.IdCondominio == modelo.IdCondominio
                                                     where referencia.NumReferencia == modelo.NumReferencia
                                                     select new { pago, referencia };

                        if (existPagoTransferencia != null && existPagoTransferencia.Any())
                        {
                            modelo = await _repoPagosEmitidos.FormPagoAnticipoNomina(modelo.IdCondominio);

                            TempData.Keep();

                            ViewBag.FormaPago = "fallido";
                            ViewBag.Mensaje = "Ya existe una transferencia con este número de referencia!";

                            return View("RegistrarAnticipoNomina", modelo);
                        }
                    }

                    var resultado = await _repoPagosEmitidos.RegistrarPagoAnticipoNomina(modelo);

                    if (resultado == "exito")
                    {
                        var condominio = await _context.Condominios.FindAsync(modelo.IdCondominio);


                        var comprobante = new ComprobanteAnticipoVM()
                        {
                            Condominio = condominio,
                            Concepto = modelo.Concepto,
                            Pagoforma = modelo.Pagoforma,
                            Mensaje = "¡Gracias por su pago!"
                        };

                        if (modelo.Pagoforma == FormaPago.Transferencia)
                        {
                            var banco = from c in _context.SubCuenta
                                        where c.Id == modelo.IdCodigoCuentaBanco
                                        select c;

                            comprobante.Banco = banco.First();
                            comprobante.NumReferencia = modelo.NumReferencia;

                        }
                        else
                        {
                            var caja = from c in _context.SubCuenta
                                       where c.Id == modelo.IdCodigoCuentaCaja
                                       select c;

Prueba/Views/AnticipoNominas/Comprobante.cshtml
@model Prueba.ViewModels.ComprobanteAnticipoVM

@{
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";
}

<!-- Begin Page Content -->
<div class="container-fluid">

    <div class="d-sm-flex align-items-center justify-content-center mb-4">
        @*<h1 class="h3 mb-0 text-gray-800">Comprobante</h1>*@
    </div>
    <div class="d-sm-flex align-items-center justify-content-around mb-4">
        @*         <a type="button" id="create_pdf" value="Generate PDF" href="#" class="d-sm-inline-block btn btn-sm btn-danger shadow-sm">
        <i class="fas fa-download fa-sm text-white-50"></i> Generar
        PDF
        </a> *@
        <button id="ComprobantePEVMPDF" class="d-sm-inline-block btn btn-sm btn-danger shadow-sm">Generar pdf</button>

    </div>

    <div class="row justify-content-center">
        <div class="col-lg-6 mb-4">


            <div class="card shadow mb-4 bg-content-bg">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">
                        Comprobante Orden de Pago
                    </h6>

                </div>
                <div class="card-body">
                    <div class="form row text-center">

                        <div class="form-group has-icon-left">
                            <div class="position-relative">
                                <form method="post">

                                    <h6>Condominio</h6>
                                    @if (Model.Condominio != null)
                                    {
                                        <input type="hidden" asp-for="@Model.Condominio.Nombre" />
                                        <p><strong>Condominio</strong>: @Model.Condominio.Nombre</p>
                                        <p><strong>RIF</strong>: @Model.Condominio.Rif</p>
                                        @* <p><strong>Inmueble</strong>: @Model.Inmueble.Nombre</p>
                                    <p><strong>Propiedad</strong>: @Model.Propiedad.Codigo</p>*@
                                    }
                                </form>
                            </div>
                        </div>
                        <div class="form-group has-icon-left">
                            <div class="position-relative">
                                <h6>Proveedor</h6>
                                <p><strong>@Model.Beneficiario</strong></p>
                            </div>
                        </div>

                        <div class="form-group has-icon-left">
                            <div class="position-relative">

                                @if (Model.Pago != null)
                                {

                                    @if (Model.Pagoforma == FormaPago.Transferencia)
                                    {
                                        <h6>Transferencia</h6>
                                        <p><strong>Fecha</strong>: @Model.Pago.Fecha.ToString("dd/MM/yyyy")</p>

                                        <p><strong>Cuenta</strong>: @Model.Banco.Descricion.ToString()</p>
                                        <p><strong>Referencia</strong>: @Model.NumReferencia</p>
                                        <p><strong>Monto</strong>: @Model.Pago.Monto.ToString("N")</p>
                                        <p><strong>Fecha de comprobante</strong>: @DateTime.Today.ToString("dd/MM/yyyy")</p>
                                    }
                                    else
                                    {
                                        <h6>Efectivo</h6>
                                        <p><strong>Cuenta</strong>: @Model.Caja.Descricion</p>
                                        <p><strong>Monto</strong>: @Model.Pago.Monto.ToString("N")</p>
                                        <p><strong>Fecha de comprobante</strong>: @(DateTime.Today.ToString("dd/MM/yyyy"))</p>
                                    }
                                }

                            </div>
                        </div>

                    </div>

                </div>

                <div class="text-center mb-4">
                    <h4 class="text-center">@Model.Mensaje</h4>

                    <a asp-action="RegistrarAnticipoNomina"
                       class="btn btn-primary me-1 mb-1">
                        Realizar otro pago
                    </a>
                    <a asp-controller="Empleados"
                       asp-action="Index"
                       class="btn btn-primary me-1 mb-1">
                        Finalizar
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>


@*PDF Configuración*@
<script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.min.js"></script>
<script>
    (function () {
        var
            form = $('.form'),
            cache_width = form.width(),
            a3 = [820, 897]; // for a4 size paper width and height
        //  a4 = [595.28, 841.89];
        // Tamaños Hojas y tamaño alto y ancho del contenido


        $('#create_pdf').on('click', function () {
            $('body').scrollTop(0);
            createPDF();
        });
        //create pdf
        function createPDF() {
            getCanvas().then(function (canvas) {
                var
                    img = canvas.toDataURL("image/png"),
                    doc = new jsPDF({
                        unit: 'px',
                        format: 'a3'
                    });

                doc.setFontSize(22)
                doc.text(20, 40, 'Comprobante')
                doc.setLineWidth(0.7)
                doc.line(20, 45, 80, 45)


                doc.addImage(img, 'JPEG', 20, 60); // xx Margen left, xx Margen Top
                // Nombre documento
                doc.save('Comprobante.pdf');
                form.width(cache_width);
            });
        }



        // create canvas object
        function getCanvas() {
            form.width((a3[0] * 1.33333) - 80).css('max-width', 'none');
            return html2canvas(form, {
                imageTimeout: 2000,
                removeContainer: true
            });
        }

    }());
</script>
<script>
    (function ($) {
        $.fn.html2canvas = function (options) {
            var date = new Date(),
                $message = null,
                timeoutTimer = false,
                timer = date.getTime();
            html2canvas.logging = options && options.logging;
            html2canvas.Preload(this[0], $.extend({
                complete: function (images) {
                    var queue = html2canvas.Parse(this[0], images, options),
                        $canvas = $(html2canvas.Renderer(queue, options)),
                        finishTime = new Date();

                    $canvas.css({ position: 'absolute', left: 0, top: 0 }).appendTo(document.body);
                    $canvas.siblings().toggle();

                    $(window).click(function () {
                        if (!$canvas.is(':visible')) {
                            $canvas.toggle().siblings().toggle();
                            throwMessage("Canvas Render visible");
                        } else {
                            $canvas.siblings().toggle();
                            $canvas.toggle();
                            throwMessage("Canvas Render hidden");
                        }
                    });
                    throwMessage('Screenshot created in ' + ((finishTime.getTime() - timer) / 1000) + " seconds<br />", 4000);
                }
            }, options));

            function throwMessage(msg, duration) {
                window.clearTimeout(timeoutTimer);
                timeoutTimer = window.setTimeout(function () {
                    $message.fadeOut(function () {
                        $message.remove();
                    });
                }, duration || 2000);
                if ($message)
                    $message.remove();
                $message = $('<div ></div>').html(msg).css({
                    margin: 0,
                    padding: 10,
                    //background: "#000",
                    //opacity: 0.7,
                    position: "fixed",
                    top: 10,
                    right: 10,
                    fontFamily: 'Tahoma',
                    //color: '#fff',
                    fontSize: 12,
                    borderRadius: 12,
                    width: 'auto',
                    height: 'auto',
                    textAlign: 'center',
                    textDecoration: 'none'
                }).hide().fadeIn().appendTo('body');
            }
        };
    })(jQuery);

</script>

<script>
    $(document).ready(function () {
        $("#ComprobantePEVMPDF").click(function () {
            var datos = @Html.Raw(Json.Serialize(Model));
            $.ajax({
                url: '/Anticipos/ComprobantePDF',
                type: 'POST',
                contentType: 'application/json',
                data: JSON.stringify(datos),
                success: function (result) {
                    var binaryData = atob(result);
                    var arrayBuffer = new ArrayBuffer(binaryData.length);
                    var uint8Array = new Uint8Array(arrayBuffer);

                    for (var i = 0; i < binaryData.length; i++) {
                        uint8Array[i] = binaryData.charCodeAt(i);
                    }

                    var blob = new Blob([uint8Array], { type: 'application/pdf' });
                    var url = URL.createObjectURL(blob);
                    var a = document.createElement('a');

                    a.style.display = 'none';
                    a.href = url;
                    a.download = 'Comprobante.pdf';
                    document.body.appendChild(a);
                    a.click();
                    document.body.removeChild(a);
                    // console.log("Exito")
                },
                error: function () {
                    alert('Error al descargar detalle del recibo');
                }
            });
        });
    });
</script>

Prueba/Views/AnticipoNominas/ConfirmarPago.cshtml
@model Prueba.ViewModels.PagoAnticipoNominaVM

@{
    ViewData["Title"] = "Pagos";
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";
}

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <!-- Content Row -->
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <!-- Illustrations -->
            <!-- DataTales Example -->
            <div class="card shadow mb-4 bg-content-bg">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">
                        Confirmar Pago
                    </h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <h6>Seguro que quiere confirmar este pago?</h6>
                        <h6>Al confirmar el pago se verá reflejado en el Libro diario</h6>
                        <hr />
                        <div>
                            <div class="card-body">
                                <div class="form form-horizontal">
                                    <div class="form-body">
                                        <dl class="row">
                                            <form asp-action="RegistrarAnticipoNomina">
                                                <input type="hidden" asp-for="IdCodigoCuentaBanco" />
                                                <input type="hidden" asp-for="IdCodigoCuentaCaja" />
                                                <label class="control-label">Forma de pago</label>
                                                @if (Model.Pagoforma == FormaPago.Efectivo)
                                                {
                                                    <input type="text" asp-for="Pagoforma" value="Efectivo" class="form-control" readonly />
                                                }
                                                else
                                                {
                                                    <input type="text" asp-for="Pagoforma" value="Transferencia" class="form-control" readonly />
                                                    <label class="control-label">Numero de Referencia</label>
                                                    <input type="text" asp-for="NumReferencia" class="form-control" readonly />

                                                }
                                                <label class="control-label">Concepto</label>
                                                <input type="text" asp-for="Concepto" class="form-control" readonly />
                                                <label class="control-label">Fecha</label>
                                                <input asp-for="Fecha" class="form-control" readonly />
                                                <label class="control-label">Monto</label>
                                                <input type="number" asp-for="Monto" class="form-control" readonly />
                                                <input type="hidden" asp-for="IdEmpleado" />
                                                <input type="hidden" asp-for="IdSubcuenta" />
                                                <hr />
                                                <button class="btn btn-primary" type="submit">Si</button>
                                                <a asp-action="PagoNomina" class="btn btn-secondary">No</a>
                                            </form>
                                        </dl>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Prueba/Views/AnticipoNominas/Create.cshtml
@model Prueba.Models.AnticipoNomina

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";

}

<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <a asp-action="Index" class="btn btn-light">Volver</a>
    </div>
    <!-- Content Row -->
    <div class="row justify-content-center">

        <div class="col-lg-6">
            <!-- Default Card Example -->
            <div class="card shadow mb-4 bg-content-bg">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">
                        Anticipos Nomina
                    </h6>
                </div>
                <div class="card-body">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="IdEmpleado" class="control-label"></label>
                            <select asp-for="IdEmpleado" class="form-control" asp-items="ViewBag.IdEmpleado"></select>
                        </div>
                        <div class="form-group">
                            <label asp-for="Monto" class="control-label"></label>
                            <input type="number" asp-for="Monto" class="form-control" />
                            <span asp-validation-for="Monto" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Fecha" class="control-label"></label>
                            <input asp-for="Fecha" class="form-control" />
                            <span asp-validation-for="Fecha" class="text-danger"></span>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="Activo" /> @Html.DisplayNameFor(model => model.Activo)
                            </label>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Crear" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Prueba/Views/AnticipoNominas/Index.cshtml
@model IEnumerable<Prueba.Models.AnticipoNomina>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";

}

<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <a class="btn btn-light mb-3" asp-controller="AnticipoNominas"
           asp-action="RegistrarAnticipoNomina">
            Registrar
        </a>
        <a class="btn btn-light mb-3"
           asp-action="Index" asp-controller="Empleados">
            Volver
        </a>
    </div>

    <!-- Content Row -->
    <div class="row">
        <div class="col-lg-12 mb-4">
            <!-- DataTales Example -->
            <div class="card shadow mb-4 bg-content-bg">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">
                        Anticipos Nomina
                    </h6>

                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table text-center"
                               id="dataTable"
                               width="100%"
                               cellspacing="0">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Monto)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Fecha)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Activo)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.IdEmpleadoNavigation)
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Monto)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Fecha)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Activo)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.IdEmpleadoNavigation.Nombre)
                                        </td>
                                        @if (item.Activo)
                                        {
                                            <td>
                                                <a asp-action="Edit" asp-route-id="@item.IdAnticipoNomina">Editar</a> |
                                                <a asp-action="Details" asp-route-id="@item.IdAnticipoNomina">Detalles</a> |
                                                <a asp-action="Delete" asp-route-id="@item.IdAnticipoNomina">Eliminar</a>
                                            </td>
                                        }
                                        else
                                        {
                                            <td>Conciliado</td>
                                        }

                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>