Prueba/Models/Cuenta.cs
using System;
using System.Collections.Generic;

namespace Prueba.Models;

public partial class Cuenta
{
    public short Id { get; set; }

    public string Descripcion { get; set; } = null!;

    public string Codigo { get; set; } = null!;

    public short IdGrupo { get; set; }

    public virtual ICollection<CodigoCuentasGlobal> CodigoCuentasGlobals { get; set; } = new List<CodigoCuentasGlobal>();

    public virtual Grupo IdGrupoNavigation { get; set; } = null!;

    public virtual ICollection<SubCuenta> SubCuenta { get; set; } = new List<SubCuenta>();
}

Prueba/Controllers/CuentasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Prueba.Context;
using Prueba.Models;

namespace Prueba.Controllers
{
    [Authorize(Policy = "RequireAdmin")]

    public class CuentasController : Controller
    {
        private readonly NuevaAppContext _context;

        public CuentasController(NuevaAppContext context)
        {
            _context = context;
        }

        // GET: Cuentas
        public async Task<IActionResult> Index()
        {
            var nuevaAppContext = _context.Cuenta.Include(c => c.IdGrupoNavigation);
            return View(await nuevaAppContext.ToListAsync());
        }

        // GET: Cuentas/Details/5
        public async Task<IActionResult> Details(short? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cuenta = await _context.Cuenta
                .Include(c => c.IdGrupoNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cuenta == null)
            {
                return NotFound();
            }

            return View(cuenta);
        }

        // GET: Cuentas/Create
        public IActionResult Create()
        {
            ViewData["IdGrupo"] = new SelectList(_context.Grupos, "Id", "Descripcion");
            return View();
        }

        // POST: Cuentas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Descripcion,Codigo,IdGrupo")] Cuenta cuenta)
        {
            ModelState.Remove(nameof(cuenta.IdGrupoNavigation));

            if (ModelState.IsValid)
            {
                _context.Add(cuenta);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdGrupo"] = new SelectList(_context.Grupos, "Id", "Descripcion", cuenta.IdGrupo);
            return View(cuenta);
        }

        // GET: Cuentas/Edit/5
        public async Task<IActionResult> Edit(short? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cuenta = await _context.Cuenta.FindAsync(id);
            if (cuenta == null)
            {
                return NotFound();
            }
            ViewData["IdGrupo"] = new SelectList(_context.Grupos, "Id", "Descripcion", cuenta.IdGrupo);
            return View(cuenta);
        }

        // POST: Cuentas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(short id, [Bind("Id,Descripcion,Codigo,IdGrupo")] Cuenta cuenta)
        {
            if (id != cuenta.Id)
            {
                return NotFound();
            }

            ModelState.Remove(nameof(cuenta.IdGrupoNavigation));


            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cuenta);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CuentaExists(cuenta.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdGrupo"] = new SelectList(_context.Grupos, "Id", "Descripcion", cuenta.IdGrupo);
            return View(cuenta);
        }

        // GET: Cuentas/Delete/5
        public async Task<IActionResult> Delete(short? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cuenta = await _context.Cuenta
                .Include(c => c.IdGrupoNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cuenta == null)
            {
                return NotFound();
            }

            return View(cuenta);
        }

        // POST: Cuentas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(short id)
        {
            var cuenta = await _context.Cuenta.FindAsync(id);
            if (cuenta != null)
            {
                _context.Cuenta.Remove(cuenta);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CuentaExists(short id)
        {
            return _context.Cuenta.Any(e => e.Id == id);
        }
    }
}

Prueba/Views/Cuentas/Create.cshtml
@model Prueba.Models.Cuenta

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";

}

<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <a asp-action="Index" class="btn btn-light">Volver</a>
    </div>
    <!-- Content Row -->
    <div class="row justify-content-center">

        <div class="col-lg-6">
            <!-- Default Card Example -->
            <div class="card shadow mb-4 bg-content-bg">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">
                        Cuentas
                    </h6>
                </div>
                <div class="card-body">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Descripcion" class="control-label"></label>
                            <input asp-for="Descripcion" class="form-control" />
                            <span asp-validation-for="Descripcion" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Codigo" class="control-label"></label>
                            <input asp-for="Codigo" class="form-control" />
                            <span asp-validation-for="Codigo" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="IdGrupo" class="control-label"></label>
                            <select asp-for="IdGrupo" class="form-control" asp-items="ViewBag.IdGrupo"></select>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Prueba/Views/Cuentas/Delete.cshtml
@model Prueba.Models.Cuenta

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";
}

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <!-- Default Card Example -->
            <div class="card shadow mb-4 bg-content-bg">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">
                        Cuentas
                    </h6>
                </div>
                <div class="card-body">
                    <div class="form form-horizontal">
                        <div class="form-body">
                            <div class="row">

                                <div class="col-md-12">
                                    <div class="card-body">
                                        <h6>Are you sure you want to delete this?</h6>

                                        <dl class="row">
                                            <dt class="col-sm-2">
                                                @Html.DisplayNameFor(model => model.Descripcion)
                                            </dt>
                                            <dd class="col-sm-10">
                                                @Html.DisplayFor(model => model.Descripcion)
                                            </dd>
                                            <dt class="col-sm-2">
                                                @Html.DisplayNameFor(model => model.Codigo)
                                            </dt>
                                            <dd class="col-sm-10">
                                                @Html.DisplayFor(model => model.Codigo)
                                            </dd>
                                            <dt class="col-sm-2">
                                                @Html.DisplayNameFor(model => model.IdGrupoNavigation)
                                            </dt>
                                            <dd class="col-sm-10">
                                                @Html.DisplayFor(model => model.IdGrupoNavigation.Descripcion)
                                            </dd>
                                        </dl>
                                        <form asp-action="Delete">
                                            <input type="hidden" asp-for="Id" />
                                            <input type="submit" value="Eliminar" class="btn btn-danger" />
                                            <a asp-action="Index" class="btn btn-secondary">Volver</a>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Prueba/Views/Cuentas/Details.cshtml
@model Prueba.Models.Cuenta

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";
}

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-6">

            <div class="card shadow mb-4 bg-content-bg">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">
                        Cuentas
                    </h6>
                </div>
                <div class="card-body">
                    <div class="form form-horizontal">
                        <div class="form-body">
                            <dl class="row">
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.Descripcion)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.Descripcion)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.Codigo)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.Codigo)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.IdGrupoNavigation)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.IdGrupoNavigation.Descripcion)
                                </dd>
                            </dl>
                            <div class="col-md-12">
                                <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-primary">Editar</a>
                                <a asp-action="Index" class="btn btn-secondary">Volver</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Prueba/Views/Cuentas/Edit.cshtml
@model Prueba.Models.Cuenta

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";
}

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <!-- Default Card Example -->
            <div class="card shadow mb-4 bg-content-bg">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">
                        Cuentas
                    </h6>
                </div>
                <div class="card-body">
                    <div class="form form-horizontal">
                        <div class="form-body">
                            <form asp-action="Edit">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <input type="hidden" asp-for="Id" />
                                <div class="form-group">
                                    <label asp-for="Descripcion" class="control-label"></label>
                                    <input asp-for="Descripcion" class="form-control" />
                                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Codigo" class="control-label"></label>
                                    <input asp-for="Codigo" class="form-control" />
                                    <span asp-validation-for="Codigo" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="IdGrupo" class="control-label"></label>
                                    <select asp-for="IdGrupo" class="form-control" asp-items="ViewBag.IdGrupo"></select>
                                    <span asp-validation-for="IdGrupo" class="text-danger"></span>
                                </div>
                                <div class="form-group pt-2">
                                    <input type="submit" value="Guardar" class="btn btn-primary" />
                                    <a asp-action="Index" class="btn btn-secondary">Volver</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Prueba/Views/Cuentas/Index.cshtml
@model IEnumerable<Prueba.Models.Cuenta>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";
}

<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        @*<h1 class="h3 mb-0 text-gray-800">Pagos Emitidos</h1>*@
        <a asp-action="Index" asp-controller="CodigoCuentasGlobals" class="btn btn-light">Volver</a>

        <a class="btn btn-light mb-3" asp-controller="Cuentas"
           asp-action="Create">
            Registrar
        </a>
    </div>
    <div class="d-sm-flex align-items-center justify-content-around mb-4">
        @*         <a type="button" id="create_pdf" value="Generate PDF" href="#" class="d-sm-inline-block btn btn-sm btn-danger shadow-sm">
        <i class="fas fa-download fa-sm text-white-50"></i> Generar
        PDF
        </a> *@
        @* <button type="button" class="d-sm-inline-block btn btn-sm btn-danger shadow-sm" id="PagosEmitidos">Crear pdf</button> *@

        @* <a value="Export" onclick="fnExcelReport();" class="d-sm-inline-block btn btn-sm btn-success shadow-sm">
        <i class="fas fa-download fa-sm text-white-50"></i> Generar
        Excel
        </a> *@
    </div>

    <!-- Content Row -->
    <div class="row">
        <div class="col-lg-12 mb-4">
            <!-- DataTales Example -->
            <div class="card shadow mb-4 bg-content-bg">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">
                        Cuentas
                    </h6>

                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table text-center"
                               id="dataTable"
                               width="100%"
                               cellspacing="0">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Descripcion)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Codigo)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.IdGrupoNavigation)
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Descripcion)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Codigo)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.IdGrupoNavigation.Descripcion)
                                        </td>
                                        <td>
                                            <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                                            <a asp-action="Details" asp-route-id="@item.Id">Detalles</a> |
                                            <a asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
                 