Prueba/Models/GrupoGasto.cs
using System;
using System.Collections.Generic;

namespace Prueba.Models;

public partial class GrupoGasto
{
    public int IdGrupoGasto { get; set; }

    public short NumGrupo { get; set; }

    public string NombreGrupo { get; set; } = null!;

    public virtual ICollection<CuentasGrupo> CuentasGrupos { get; set; } = new List<CuentasGrupo>();

    public virtual ICollection<PropiedadesGrupo> PropiedadesGrupos { get; set; } = new List<PropiedadesGrupo>();
}

Prueba/Controllers/GrupoGastosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Prueba.Context;
using Prueba.Models;

namespace Prueba.Controllers
{
    [Authorize(Policy = "RequireAdmin")]
    public class GrupoGastosController : Controller
    {
        private readonly NuevaAppContext _context;

        public GrupoGastosController(NuevaAppContext context)
        {
            _context = context;
        }

        // GET: GrupoGastos
        public async Task<IActionResult> Index()
        {
            return View(await _context.GrupoGastos.ToListAsync());
        }

        // GET: GrupoGastos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grupoGasto = await _context.GrupoGastos
                .FirstOrDefaultAsync(m => m.IdGrupoGasto == id);
            if (grupoGasto == null)
            {
                return NotFound();
            }

            return View(grupoGasto);
        }

        // GET: GrupoGastos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: GrupoGastos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdGrupoGasto,NumGrupo,NombreGrupo")] GrupoGasto grupoGasto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(grupoGasto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(grupoGasto);
        }

        // GET: GrupoGastos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grupoGasto = await _context.GrupoGastos.FindAsync(id);
            if (grupoGasto == null)
            {
                return NotFound();
            }
            return View(grupoGasto);
        }

        // POST: GrupoGastos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdGrupoGasto,NumGrupo,NombreGrupo")] GrupoGasto grupoGasto)
        {
            if (id != grupoGasto.IdGrupoGasto)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(grupoGasto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GrupoGastoExists(grupoGasto.IdGrupoGasto))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(grupoGasto);
        }

        // GET: GrupoGastos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grupoGasto = await _context.GrupoGastos
                .FirstOrDefaultAsync(m => m.IdGrupoGasto == id);
            if (grupoGasto == null)
            {
                return NotFound();
            }

            return View(grupoGasto);
        }

        // POST: GrupoGastos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var grupoGasto = await _context.GrupoGastos.FindAsync(id);
            if (grupoGasto != null)
            {
                IList<CuentasGrupo> cuentasGrupos = await _context.CuentasGrupos.Where(c => c.IdGrupoGasto == id).ToListAsync();
                IList<PropiedadesGrupo> propiedadesGrupos = await _context.PropiedadesGrupos.Where(c => c.IdGrupoGasto == id).ToListAsync();

                if (cuentasGrupos.Any())
                {
                    _context.CuentasGrupos.RemoveRange(cuentasGrupos);
                }

                if (propiedadesGrupos.Any())
                {
                    _context.PropiedadesGrupos.RemoveRange(propiedadesGrupos);
                }

                _context.GrupoGastos.Remove(grupoGasto);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Accion para llevar a la vista index de cuentas en un grupo
        /// </summary>
        /// <param name="id">id del grupo para buscar sus cuentas</param>
        /// <returns></returns>
        public async Task<IActionResult> VerCuentas(int id)
        {
            // buscar cuentas del grupo
            var cuentasGrupos = await (from g in _context.GrupoGastos
                                join cg in _context.CuentasGrupos
                                on g.IdGrupoGasto equals cg.IdGrupoGasto
                                join cc in _context.CodigoCuentasGlobals
                                on cg.IdCodCuenta equals cc.IdCodCuenta
                                join sc in _context.SubCuenta
                                on cc.IdSubCuenta equals sc.Id
                                where g.IdGrupoGasto == id
                                select sc).ToListAsync();

            TempData["IDGrupo"] = id.ToString();
            //ViewData["NombreGrupo"] = id;

            return View(cuentasGrupos);
        }

        public IActionResult AgregarCuenta()
        {
            return RedirectToAction("Create", "CuentasGrupos");
        }

        private bool GrupoGastoExists(int id)
        {
            return _context.GrupoGastos.Any(e => e.IdGrupoGasto == id);
        }

        public async Task<IActionResult> EliminarCuentaGrupo(int? id)
        {
            var idGrupo = Convert.ToInt32(TempData.Peek("IDGrupo").ToString());

            if (id == null)
            {
                return NotFound();
            }

            var subcuenta = await _context.SubCuenta
                .FirstOrDefaultAsync(m => m.Id == id);

            if (subcuenta == null)
            {
                return NotFound();
            }

            TempData.Keep();

            return View(subcuenta);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id">ID de la subcuenta a eliminar del grupo</param>
        /// <returns></returns>
        [HttpPost, ActionName("EliminarCuentaGrupo")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EliminarCuentaGrupoConfirmed(int id)
        {
            var idGrupo = Convert.ToInt32(TempData.Peek("IDGrupo").ToString());

            var idCC = from c in _context.CodigoCuentasGlobals
                       where c.IdSubCuenta == id
                       select c;

            if (!idCC.Any())
            {
                return NotFound();
            }

            var cuentaGrupo = (from c in _context.CuentasGrupos
                              where c.IdGrupoGasto == idGrupo && c.IdCodCuenta == idCC.First().IdCodCuenta
                              select c).First();

            if (cuentaGrupo == null)
            {
                return NotFound();
            }

            _context.CuentasGrupos.Remove(cuentaGrupo);
            await _context.SaveChangesAsync();

            return RedirectToAction("VerCuentas", new { id = idGrupo });

        }
    }
}

Prueba/Views/GrupoGastos/Create.cshtml
@model Prueba.Models.GrupoGasto

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";

}

<div class="container-fluid">
    <!-- Page Heading -->
    @*    <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Registrar Pagos</h1>
    </div>*@
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <a asp-action="Index" class="btn btn-light">Volver</a>
    </div>
    <!-- Content Row -->
    <div class="row justify-content-center">

        <div class="col-lg-6">
            <!-- Default Card Example -->
            <div class="card shadow mb-4 bg-content-bg">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">
                        Grupos Gastos
                    </h6>
                </div>
                <div class="card-body">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="NumGrupo" class="control-label"></label>
                            <input asp-for="NumGrupo" class="form-control" />
                            <span asp-validation-for="NumGrupo" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="NombreGrupo" class="control-label"></label>
                            <input asp-for="NombreGrupo" class="form-control" />
                            <span asp-validation-for="NombreGrupo" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Crear" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Prueba/Views/GrupoGastos/Delete.cshtml
@model Prueba.Models.GrupoGasto

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";

}

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <!-- Default Card Example -->
            <div class="card shadow mb-4 bg-content-bg">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">
                        Grupos Gastos
                    </h6>
                </div>
                <div class="card-body">
                    <div class="form form-horizontal">
                        <div class="form-body">
                            <div class="row">

                                <div class="col-md-12">
                                    <div class="card-body">
                                        <h6>Are you sure you want to delete this?</h6>

                                        <dl class="row">
                                            <dt class="col-sm-2">
                                                @Html.DisplayNameFor(model => model.NumGrupo)
                                            </dt>
                                            <dd class="col-sm-10">
                                                @Html.DisplayFor(model => model.NumGrupo)
                                            </dd>
                                            <dt class="col-sm-2">
                                                @Html.DisplayNameFor(model => model.NombreGrupo)
                                            </dt>
                                            <dd class="col-sm-10">
                                                @Html.DisplayFor(model => model.NombreGrupo)
                                            </dd>
                                        </dl>
                                        <form asp-action="Delete">
                                            <input type="hidden" asp-for="IdGrupoGasto" />
                                            <input type="submit" value="Eliminar" class="btn btn-danger" />
                                            <a asp-action="Index" class="btn btn-secondary">Volver</a>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Prueba/Views/GrupoGastos/Details.cshtml
@model Prueba.Models.GrupoGasto

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";

}

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-6">

            <div class="card shadow mb-4 bg-content-bg">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">
                        Grupos Gastos
                    </h6>
                </div>
                <div class="card-body">
                    <div class="form form-horizontal">
                        <div class="form-body">
                            <dl class="row">
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.NumGrupo)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.NumGrupo)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.NombreGrupo)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.NombreGrupo)
                                </dd>
                            </dl>
                            <div class="col-md-12">
                                <a asp-action="Edit" asp-route-id="@Model?.IdGrupoGasto" class="btn btn-primary">Editar</a>
                                <a asp-action="Index" class="btn btn-secondary">Volver</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
                          

Prueba/Views/GrupoGastos/Edit.cshtml
@model Prueba.Models.GrupoGasto

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";

}

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <!-- Default Card Example -->
            <div class="card shadow mb-4 bg-content-bg">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">
                        Grupos Gastos
                    </h6>
                </div>
                <div class="card-body">
                    <div class="form form-horizontal">
                        <div class="form-body">
                            <form asp-action="Edit">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <input type="hidden" asp-for="IdGrupoGasto" />
                                <div class="form-group">
                                    <label asp-for="NumGrupo" class="control-label"></label>
                                    <input asp-for="NumGrupo" class="form-control" />
                                    <span asp-validation-for="NumGrupo" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="NombreGrupo" class="control-label"></label>
                                    <input asp-for="NombreGrupo" class="form-control" />
                                    <span asp-validation-for="NombreGrupo" class="text-danger"></span>
                                </div>
                                <div class="form-group pt-2">
                                    <input type="submit" value="Guardar" class="btn btn-primary" />
                                    <a asp-action="Index" class="btn btn-secondary">Volver</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Prueba/Views/GrupoGastos/EliminarCuentaGrupo.cshtml
@model Prueba.Models.SubCuenta

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";
}

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <!-- Default Card Example -->
            <div class="card shadow mb-4 bg-content-bg">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">
                        Cuentas de Grupo
                    </h6>
                </div>
                <div class="card-body">
                    <div class="form form-horizontal">
                        <div class="form-body">
                            <div class="row">

                                <div class="col-md-12">
                                    <div class="card-body">
                                        <h6>Seguro que desea eliminar esta cuenta del grupo?</h6>
                                        <hr />

                                        <dl class="row">
                                            <dt class="col-sm-2">
                                                @Html.DisplayNameFor(model => model.Descricion)
                                            </dt>
                                            <dd class="col-sm-10">
                                                @Html.DisplayFor(model => model.Descricion)
                                            </dd>
                                            <dt class="col-sm-2">
                                                @Html.DisplayNameFor(model => model.Codigo)
                                            </dt>
                                            <dd class="col-sm-10">
                                                @Html.DisplayFor(model => model.Codigo)
                                            </dd>
                                        </dl>

                                        <form asp-action="EliminarCuentaGrupo">
                                            <input type="hidden" asp-for="Id" />
                                            <input type="submit" value="Eliminar" class="btn btn-danger" />
                                            <a asp-action="Index" class="btn btn-secondary">Volver</a>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Prueba/Views/GrupoGastos/Index.cshtml
@model IEnumerable<Prueba.Models.GrupoGasto>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";

}


<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <a class="btn btn-light mb-3" asp-controller="GrupoGastos"
           asp-action="Create">
            Registrar
        </a>
        @* <a class="btn btn-light mb-3" asp-controller="Grupos"
           asp-action="Index">
            Grupos
        </a> *@
    </div>
    <div class="d-sm-flex align-items-center justify-content-around mb-4">
        @*         <a type="button" id="create_pdf" value="Generate PDF" href="#" class="d-sm-inline-block btn btn-sm btn-danger shadow-sm">
        <i class="fas fa-download fa-sm text-white-50"></i> Generar
        PDF
        </a> *@
        @* <button type="button" class="d-sm-inline-block btn btn-sm btn-danger shadow-sm" id="PagosEmitidos">Crear pdf</button> *@

        @* <a value="Export" onclick="fnExcelReport();" class="d-sm-inline-block btn btn-sm btn-success shadow-sm">
        <i class="fas fa-download fa-sm text-white-50"></i> Generar
        Excel
        </a> *@
    </div>

    <!-- Content Row -->
    <div class="row">
        <div class="col-lg-12 mb-4">
            <!-- DataTales Example -->
            <div class="card shadow mb-4 bg-content-bg">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">
                        Grupos Gastos
                    </h6>

                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.NumGrupo)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.NombreGrupo)
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.NumGrupo)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.NombreGrupo)
                                        </td>
                                        <td>
                                            <a asp-action="VerCuentas" asp-route-id="@item.IdGrupoGasto">Ver cuentas</a> |
                                            <a asp-action="Edit" asp-route-id="@item.IdGrupoGasto">Editar</a> |
                                            <a asp-action="Details" asp-route-id="@item.IdGrupoGasto">Detalles</a> |
                                            <a asp-action="Delete" asp-route-id="@item.IdGrupoGasto">Eliminar</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Prueba/Views/GrupoGastos/VerCuentas.cshtml
@model IEnumerable<SubCuenta>

@{
    ViewData["Title"] = "Cuentas de Grupo";
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";
}

<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <a class="btn btn-light mb-3"
           asp-action="AgregarCuenta">
            Agregar Cuenta
        </a>
        <a class="btn btn-light mb-3" asp-controller="GrupoGastos"
        asp-action="Index">
        Volver
        </a>
    </div>
    <div class="d-sm-flex align-items-center justify-content-around mb-4">
        @*         <a type="button" id="create_pdf" value="Generate PDF" href="#" class="d-sm-inline-block btn btn-sm btn-danger shadow-sm">
        <i class="fas fa-download fa-sm text-white-50"></i> Generar
        PDF
        </a> *@
        @* <button type="button" class="d-sm-inline-block btn btn-sm btn-danger shadow-sm" id="PagosEmitidos">Crear pdf</button> *@

        @* <a value="Export" onclick="fnExcelReport();" class="d-sm-inline-block btn btn-sm btn-success shadow-sm">
        <i class="fas fa-download fa-sm text-white-50"></i> Generar
        Excel
        </a> *@
    </div>

    <!-- Content Row -->
    <div class="row">
        <div class="col-lg-12 mb-4">
            <!-- DataTales Example -->
            <div class="card shadow mb-4 bg-content-bg">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">
                        Cuentas de un Grupos
                    </h6>

                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Descricion)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Codigo)
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Descricion)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Codigo)
                                        </td>
                                        <td>
                                            <a asp-action="EliminarCuentaGrupo" asp-route-id="@item.Id">Eliminar del Grupo</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>